service: ${self:custom.defaults.service}
frameworkVersion: "3"
useDotenv: true
plugins:
  - serverless-esbuild
  - serverless-prune-plugin
  - serverless-dotenv-plugin
  - serverless-deployment-bucket
provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  deploymentBucket:
    name: ${self:custom.params.DEPLOYMENT_BUCKET}

custom:
  defaults: ${file(./defaults.yml)}
  base: ${self:service}-${self:provider.stage}
  params: ${self:custom.defaults.custom.params.${self:provider.stage}}
  prune:  ${file(./defaults.yml):custom.prune}
  iam:
    SaveFlightLambdaRole:
      name: ${self:custom.base}-save-flight-lambda-role
    RemoveFlightLambdaRole:
      name: ${self:custom.base}-remove-flight-lambda-role
package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!lambda-layer/**"
    - "!resources/**"
    - "!.env*"
functions:
  - ${file(./resources/functions/saveFlight.yml)}
  - ${file(./resources/functions/removeFlight.yml)}
resources:
  - ${file(./resources/sqs.yml)}
  - ${file(./resources/dynamodb.yml)}
  - ${file(./resources/iam/lambdaRemoveFlightRole.yml)}
  - ${file(./resources/iam/lambdaSaveFlightRole.yml)}
