service: ${self:custom.defaults.service}
frameworkVersion: "3"
useDotenv: true
plugins:
  - serverless-esbuild
  - serverless-prune-plugin
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  deploymentBucket:
    name: ${self:custom.params.DEPLOYMENT_BUCKET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:BatchWriteItem
            - dynamodb:BatchGetItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.params.DYNAMODB_TABLE}"
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${self:custom.params.S3_BUCKET}/*"
custom:
  defaults: ${file(./defaults.yml)}
  params: ${self:custom.defaults.custom.params.${self:provider.stage}}
  prune:  ${file(./defaults.yml):custom.prune}
package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!lambda-layer/**"
    - "!resources/**"
    - "!.env*"
functions:
  - ${file(./resources/functions/saveFlight.yml)}
  - ${file(./resources/functions/removeFlight.yml)}
resources:
  - ${file(./resources/sqs.yml)}
  - ${file(./resources/dynamodb.yml)}
