service: myserverless
frameworkVersion: "3"
useDotenv: true
plugins:
  - serverless-esbuild
  - serverless-prune-plugin
provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.environment.DEPLOYMENT_BUCKET}
  environment:
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    S3_BUCKET: ${env:S3_BUCKET}
    FLIGHT_QUEUE: ${env:FLIGHT_QUEUE}
    LAYER_VERSION: ${env:LAYER_VERSION}
    DEPLOYMENT_BUCKET: ${env:DEPLOYMENT_BUCKET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
package:
  patterns:
    - "!node_modules/**"
    - "!lambda-layer/**"
    - "!resources/**"
    - "!.env*"
functions:
  - ${file(./resources/functions/saveFlight.yml)}
  - ${file(./resources/functions/removeFlight.yml)}
resources:
  - ${file(./resources/sqs.yml)}
  - ${file(./resources/dynamodb.yml)}
