service: myserverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  region: us-east-1
  environment:
    DYNAMODB_TABLE: flights
    S3_BUCKET: flight-ojijhbudasdash-1qaz2wsx
    FLIGHT_QUEUE: flightQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"

functions:
  - ${file(./resources/functions/saveFlight.yml)}
  - ${file(./resources/functions/removeFlight.yml)}

resources:
  - ${file(./resources/sqs.yml)}
  - ${file(./resources/dynamodb.yml)}
