service: myserverless

frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser

functions:
  - ${file(./resources/functions/saveFlight.yml)}

resources:
  - ${file(./resources/sqs.yml)}
  - ${file(./resources/dynamodb.yml)}
  # - ${file(./resources/s3.yml)}

