service: lambda-layer
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, "us-east-1"}

layers:
  FlightNodeModulesLayer:
    path: flight_modules/node_modules
    description: "Node modules Dependencies"
    compatibleRuntimes:
      - "nodejs18.x"
